version: '3'

services:
  keyclock:
    container_name: keyclock-server
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - ${KEYLOACK_PORT}:${KEYLOACK_PORT}
    command:
      - start-dev